package dao;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

/**
 * Verifies that a database created by a previous version of the application,
 * where the tables had no foreign keys, is upgraded in place by
 * {@link SchemaInitializer} without losing the data it already contains.
 */
class SchemaUpgradeTest {

    private Connection connection;

    @BeforeEach
    void setUp() throws SQLException {
        connection = DriverManager.getConnection(
                "jdbc:h2:mem:upgrade_" + System.nanoTime(), "sa", "");
        createLegacySchema();
    }

    @AfterEach
    void tearDown() throws SQLException {
        connection.close();
    }

    /** The schema as the DAOs used to create it: no foreign keys, no indexes. */
    private void createLegacySchema() throws SQLException {
        execute("CREATE TABLE animals (microchip_id VARCHAR(50) PRIMARY KEY, "
                + "animal_type VARCHAR(20), breed VARCHAR(100), intake_date DATE, "
                + "estimated_age INT, health_status VARCHAR(50), photo_path VARCHAR(255), "
                + "status VARCHAR(50))");
        execute("CREATE TABLE health_records (id INT GENERATED BY DEFAULT AS IDENTITY "
                + "PRIMARY KEY, microchip_id VARCHAR(50), treatment_type VARCHAR(40), "
                + "description VARCHAR(255), treatment_date DATE, dosage VARCHAR(50))");
        execute("INSERT INTO animals (microchip_id, animal_type, breed, intake_date, "
                + "estimated_age, health_status, photo_path, status) VALUES "
                + "('LEGACY-1', 'CAT', 'Siamese', DATE '2026-01-10', 2, "
                + "'UNDER_OBSERVATION', 'photos/unknown.jpg', 'IN_OBSERVATION')");
        execute("INSERT INTO health_records (microchip_id, treatment_type, description, "
                + "treatment_date, dosage) VALUES ('LEGACY-1', 'VACCINE', 'Rabies', "
                + "DATE '2026-01-12', '1ml')");
    }

    private void execute(String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    private int count(String table) throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet rs = statement.executeQuery("SELECT COUNT(*) FROM " + table)) {
            rs.next();
            return rs.getInt(1);
        }
    }

    @Test
    void keepsTheExistingDataAfterTheUpgrade() throws SQLException {
        SchemaInitializer.initialize(connection);

        assertEquals(1, count("animals"));
        assertEquals(1, count("health_records"));
    }

    @Test
    void addsTheMissingTablesToAnOlderDatabase() throws SQLException {
        SchemaInitializer.initialize(connection);

        assertEquals(0, count("adopters"));
        assertEquals(0, count("adoptions"));
        assertEquals(0, count("kennels"));
        assertEquals(0, count("status_change_log"));
    }

    @Test
    void enforcesReferentialIntegrityAfterTheUpgrade() throws SQLException {
        SchemaInitializer.initialize(connection);

        assertThrows(SQLException.class, () -> execute(
                "INSERT INTO health_records (microchip_id, treatment_type, description, "
                        + "treatment_date, dosage) VALUES ('NOT-REGISTERED', 'VACCINE', "
                        + "'Rabies', DATE '2026-08-30', '1ml')"));
    }
}
