package dao;

import model.Adoption;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.Month;
import java.util.EnumMap;
import java.util.Map;

/**
 * JDBC implementation of {@link AdoptionDAO}.
 */
public class JdbcAdoptionDAO implements AdoptionDAO {
    private final Connection connection;

    public JdbcAdoptionDAO(Connection connection) {
        this.connection = connection;
        createTableIfNeeded();
    }

    @Override
    public void save(Adoption adoption) {
        String sql = "INSERT INTO adoptions (animal_id, adopter_id, placement_date) "
                + "VALUES (?, ?, ?)";
        try (PreparedStatement stmt = connection.prepareStatement(sql)) {
            stmt.setString(1, adoption.getAnimalId());
            stmt.setString(2, adoption.getAdopterId());
            stmt.setDate(3, java.sql.Date.valueOf(adoption.getPlacementDate()));
            stmt.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException("Failed to save adoption", e);
        }
    }

    @Override
    public Map<Month, Integer> getMonthlyAdoptions(int year) {
        Map<Month, Integer> results = new EnumMap<>(Month.class);
        String sql = "SELECT placement_date FROM adoptions "
                + "WHERE placement_date >= ? AND placement_date < ?";
        LocalDate from = LocalDate.of(year, 1, 1);
        LocalDate to = from.plusYears(1);

        try (PreparedStatement stmt = connection.prepareStatement(sql)) {
            stmt.setDate(1, Date.valueOf(from));
            stmt.setDate(2, Date.valueOf(to));
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    Month month = rs.getDate("placement_date").toLocalDate().getMonth();
                    results.put(month, results.getOrDefault(month, 0) + 1);
                }
            }
        } catch (SQLException e) {
            throw new RuntimeException("Failed to load adoption statistics", e);
        }

        return results;
    }

    private void createTableIfNeeded() {
        String sql = "CREATE TABLE IF NOT EXISTS adoptions ("
                + "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "animal_id VARCHAR(50), "
                + "adopter_id VARCHAR(50), "
                + "placement_date DATE"
                + ")";
        try (PreparedStatement stmt = connection.prepareStatement(sql)) {
            stmt.execute();
        } catch (SQLException e) {
            throw new RuntimeException("Failed to create adoptions table", e);
        }
    }
}
