package dao;

import model.Animal;
import model.StatusChangeLog;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

/**
 * JDBC implementation of {@link StatusChangeLogDAO}.
 */
public class JdbcStatusChangeLogDAO implements StatusChangeLogDAO {
    private final Connection connection;

    public JdbcStatusChangeLogDAO(Connection connection) {
        this.connection = connection;
        createTableIfNeeded();
    }

    @Override
    public void save(StatusChangeLog log) {
        String sql = "INSERT INTO status_change_log "
                + "(microchip_id, old_status, new_status, change_date) "
                + "VALUES (?, ?, ?, ?)";
        try (PreparedStatement stmt = connection.prepareStatement(sql)) {
            stmt.setString(1, log.getMicrochipId());
            stmt.setString(2, log.getOldStatus() == null ? null : log.getOldStatus().name());
            stmt.setString(3, log.getNewStatus().name());
            stmt.setTimestamp(4, Timestamp.valueOf(log.getTimestamp()));
            stmt.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException("Failed to save status change log", e);
        }
    }

    @Override
    public List<StatusChangeLog> findByAnimal(String microchipId) {
        String sql = "SELECT microchip_id, old_status, new_status, change_date "
                + "FROM status_change_log WHERE microchip_id = ? "
                + "ORDER BY change_date ASC, id ASC";

        List<StatusChangeLog> results = new ArrayList<>();
        try (PreparedStatement stmt = connection.prepareStatement(sql)) {
            stmt.setString(1, microchipId);
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    String oldStatusValue = rs.getString("old_status");
                    Animal.Status oldStatus = oldStatusValue == null
                            ? null
                            : Animal.Status.valueOf(oldStatusValue);
                    Animal.Status newStatus =
                            Animal.Status.valueOf(rs.getString("new_status"));
                    results.add(new StatusChangeLog(
                            rs.getString("microchip_id"),
                            oldStatus,
                            newStatus,
                            rs.getTimestamp("change_date").toLocalDateTime()
                    ));
                }
            }
        } catch (SQLException e) {
            throw new RuntimeException("Failed to load status change logs", e);
        }

        return results;
    }

    private void createTableIfNeeded() {
        String sql = "CREATE TABLE IF NOT EXISTS status_change_log ("
                + "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "microchip_id VARCHAR(50), "
                + "old_status VARCHAR(50), "
                + "new_status VARCHAR(50), "
                + "change_date TIMESTAMP"
                + ")";
        try (PreparedStatement stmt = connection.prepareStatement(sql)) {
            stmt.execute();
        } catch (SQLException e) {
            throw new RuntimeException("Failed to create status_change_log table", e);
        }
    }
}
