package dao;

import model.HealthRecord;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * JDBC implementation of {@link HealthRecordDAO}.
 */
public class JdbcHealthRecordDAO implements HealthRecordDAO {
    private final Connection connection;

    public JdbcHealthRecordDAO(Connection connection) {
        this.connection = connection;
        createTableIfNeeded();
    }

    @Override
    public void save(HealthRecord record) {
        String sql = "INSERT INTO health_records "
                + "(microchip_id, treatment_type, description, treatment_date, dosage) "
                + "VALUES (?, ?, ?, ?, ?)";
        try (PreparedStatement stmt = connection.prepareStatement(sql)) {
            stmt.setString(1, record.getMicrochipId());
            stmt.setString(2, record.getTreatmentType().name());
            stmt.setString(3, record.getDescription());
            stmt.setDate(4, Date.valueOf(record.getDate()));
            stmt.setString(5, record.getDosage());
            stmt.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException("Failed to save health record", e);
        }
    }

    @Override
    public List<HealthRecord> findByMicrochipId(String microchipId) {
        String sql = "SELECT microchip_id, treatment_type, description, treatment_date, dosage "
                + "FROM health_records WHERE microchip_id = ? ORDER BY treatment_date ASC";
        List<HealthRecord> result = new ArrayList<>();
        try (PreparedStatement stmt = connection.prepareStatement(sql)) {
            stmt.setString(1, microchipId);
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    result.add(mapRow(rs));
                }
            }
            return result;
        } catch (SQLException e) {
            throw new RuntimeException("Failed to load health records by microchip", e);
        }
    }

    @Override
    public List<HealthRecord> findAll() {
        String sql = "SELECT microchip_id, treatment_type, description, treatment_date, dosage "
                + "FROM health_records";
        List<HealthRecord> result = new ArrayList<>();
        try (PreparedStatement stmt = connection.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {
            while (rs.next()) {
                result.add(mapRow(rs));
            }
            return result;
        } catch (SQLException e) {
            throw new RuntimeException("Failed to load health records", e);
        }
    }

    private HealthRecord mapRow(ResultSet rs) throws SQLException {
        return new HealthRecord(
                rs.getString("microchip_id"),
                HealthRecord.TreatmentType.valueOf(rs.getString("treatment_type")),
                rs.getString("description"),
                rs.getDate("treatment_date").toLocalDate(),
                rs.getString("dosage")
        );
    }

    private void createTableIfNeeded() {
        String sql = "CREATE TABLE IF NOT EXISTS health_records ("
                + "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "microchip_id VARCHAR(50), "
                + "treatment_type VARCHAR(40), "
                + "description VARCHAR(255), "
                + "treatment_date DATE, "
                + "dosage VARCHAR(50)"
                + ")";
        try (PreparedStatement stmt = connection.prepareStatement(sql)) {
            stmt.execute();
        } catch (SQLException e) {
            throw new RuntimeException("Failed to create health_records table", e);
        }
    }
}
