package dao;

import util.LoggerConfig;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Creates the relational schema of the application in dependency order and
 * enforces its referential integrity.
 *
 * <p>Each DAO is able to create its own table lazily, but doing so gives no
 * control over the creation order, which makes it impossible to declare
 * foreign keys: a child table cannot reference a parent table that does not
 * exist yet. This initializer is therefore executed once, at start-up, before
 * any DAO is built:</p>
 *
 * <ol>
 *   <li>parent tables first ({@code animals}, {@code adopters},
 *       {@code kennels}), then the child tables that reference them;</li>
 *   <li>foreign keys and check constraints, added with
 *       {@code IF NOT EXISTS} so that a database created by an earlier
 *       version of the application is upgraded in place;</li>
 *   <li>indexes for the most frequent lookups.</li>
 * </ol>
 *
 * <p>Table creation is mandatory: if it fails the application cannot run and
 * the error is propagated. Constraints and indexes are best effort: on a
 * legacy database that already contains rows violating a constraint the
 * statement is skipped and a warning is logged, so the application still
 * starts and the problem is visible in {@code logs/shelter.log}.</p>
 *
 * <p>The same schema is documented, for reference, in {@code db/schema.sql}.</p>
 */
public final class SchemaInitializer {

    private static final Logger logger = LoggerConfig.getLogger(SchemaInitializer.class);

    /** Parent tables first, then the tables that reference them. */
    private static final List<String> TABLES = List.of(
            "CREATE TABLE IF NOT EXISTS animals ("
                    + "microchip_id VARCHAR(50) PRIMARY KEY, "
                    + "animal_type VARCHAR(20), "
                    + "breed VARCHAR(100), "
                    + "intake_date DATE, "
                    + "estimated_age INT, "
                    + "health_status VARCHAR(50), "
                    + "photo_path VARCHAR(255), "
                    + "status VARCHAR(50))",

            "CREATE TABLE IF NOT EXISTS adopters ("
                    + "adopter_id VARCHAR(50) PRIMARY KEY, "
                    + "full_name VARCHAR(150), "
                    + "phone VARCHAR(40), "
                    + "preferred_species VARCHAR(40), "
                    + "preferred_breed VARCHAR(100))",

            "CREATE TABLE IF NOT EXISTS kennels ("
                    + "kennel_id VARCHAR(50) PRIMARY KEY, "
                    + "space_type VARCHAR(30), "
                    + "max_capacity INT, "
                    + "occupied INT)",

            "CREATE TABLE IF NOT EXISTS health_records ("
                    + "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "microchip_id VARCHAR(50), "
                    + "treatment_type VARCHAR(40), "
                    + "description VARCHAR(255), "
                    + "treatment_date DATE, "
                    + "dosage VARCHAR(50))",

            "CREATE TABLE IF NOT EXISTS adoptions ("
                    + "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "animal_id VARCHAR(50), "
                    + "adopter_id VARCHAR(50), "
                    + "placement_date DATE)",

            "CREATE TABLE IF NOT EXISTS status_change_log ("
                    + "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "microchip_id VARCHAR(50), "
                    + "old_status VARCHAR(50), "
                    + "new_status VARCHAR(50), "
                    + "change_date TIMESTAMP)"
    );

    /** Referential integrity and domain invariants. */
    private static final List<String> CONSTRAINTS = List.of(
            "ALTER TABLE health_records ADD CONSTRAINT IF NOT EXISTS fk_health_animal "
                    + "FOREIGN KEY (microchip_id) REFERENCES animals (microchip_id) ON DELETE CASCADE",

            "ALTER TABLE adoptions ADD CONSTRAINT IF NOT EXISTS fk_adoption_animal "
                    + "FOREIGN KEY (animal_id) REFERENCES animals (microchip_id)",

            "ALTER TABLE adoptions ADD CONSTRAINT IF NOT EXISTS fk_adoption_adopter "
                    + "FOREIGN KEY (adopter_id) REFERENCES adopters (adopter_id)",

            "ALTER TABLE status_change_log ADD CONSTRAINT IF NOT EXISTS fk_log_animal "
                    + "FOREIGN KEY (microchip_id) REFERENCES animals (microchip_id) ON DELETE CASCADE",

            "ALTER TABLE kennels ADD CONSTRAINT IF NOT EXISTS chk_kennel_capacity "
                    + "CHECK (occupied >= 0 AND occupied <= max_capacity)"
    );

    /** Indexes for the most frequent lookups. */
    private static final List<String> INDEXES = List.of(
            "CREATE INDEX IF NOT EXISTS idx_animals_status ON animals (status)",
            "CREATE INDEX IF NOT EXISTS idx_health_animal ON health_records (microchip_id)",
            "CREATE INDEX IF NOT EXISTS idx_health_date ON health_records (treatment_date)",
            "CREATE INDEX IF NOT EXISTS idx_adoptions_animal ON adoptions (animal_id)",
            "CREATE INDEX IF NOT EXISTS idx_adoptions_adopter ON adoptions (adopter_id)",
            "CREATE INDEX IF NOT EXISTS idx_adoptions_date ON adoptions (placement_date)",
            "CREATE INDEX IF NOT EXISTS idx_log_animal ON status_change_log (microchip_id)"
    );

    private SchemaInitializer() {
    }

    /**
     * Creates the schema and enforces its constraints on the given connection.
     *
     * @param connection open JDBC connection; must not be null.
     * @throws IllegalStateException if a table cannot be created.
     */
    public static void initialize(Connection connection) {
        if (connection == null) {
            throw new IllegalArgumentException("Connection is required");
        }
        run(connection, TABLES, true);
        run(connection, CONSTRAINTS, false);
        run(connection, INDEXES, false);
        logger.info("event=schema_initialized tables=" + TABLES.size()
                + " constraints=" + CONSTRAINTS.size() + " indexes=" + INDEXES.size());
    }

    private static void run(Connection connection, List<String> statements, boolean mandatory) {
        for (String sql : statements) {
            try (Statement statement = connection.createStatement()) {
                statement.execute(sql);
            } catch (SQLException e) {
                if (mandatory) {
                    throw new IllegalStateException("Schema initialization failed: " + sql, e);
                }
                logger.log(Level.WARNING, "event=schema_statement_skipped reason="
                        + e.getMessage() + " sql=" + sql);
            }
        }
    }
}
