-- =====================================================================
-- Pet Shelter and Adoption Management System
-- Project 11 - Software Engineering 2025/2026 - University of Cassino
--
-- Relational schema (H2, file mode: jdbc:h2:file:./data/petshelter)
--
-- The application creates these tables automatically at start-up
-- (see dao/Jdbc*DAO.java -> ensureTable()). This file documents the
-- schema, its keys, its referential integrity and its indexes, and can
-- be executed manually to initialise an empty database.
-- =====================================================================

-- ---------------------------------------------------------------------
-- ANIMALS: core registry. One row per sheltered animal.
-- microchip_id is the natural business key used across the whole system.
-- animal_type discriminates the Java subclasses (Dog / Cat).
-- status: IN_OBSERVATION | UNDER_TREATMENT | READY_FOR_ADOPTION | ADOPTED
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS animals (
    microchip_id   VARCHAR(50)  PRIMARY KEY,
    animal_type    VARCHAR(20)  NOT NULL,
    breed          VARCHAR(100),
    intake_date    DATE         NOT NULL,
    estimated_age  INT,
    health_status  VARCHAR(50),
    photo_path     VARCHAR(255),
    status         VARCHAR(50)  NOT NULL
);

-- ---------------------------------------------------------------------
-- ADOPTERS: people registered as potential adopters.
-- preferred_species / preferred_breed drive the compatibility matching.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS adopters (
    adopter_id        VARCHAR(50)  PRIMARY KEY,
    full_name         VARCHAR(150) NOT NULL,
    phone             VARCHAR(40),
    preferred_species VARCHAR(40),
    preferred_breed   VARCHAR(100)
);

-- ---------------------------------------------------------------------
-- KENNELS: physical shelter spaces with capacity control.
-- space_type: KENNEL | CAGE | FENCED_AREA
-- occupied is kept <= max_capacity by KennelService (transactional check).
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS kennels (
    kennel_id    VARCHAR(50) PRIMARY KEY,
    space_type   VARCHAR(30) NOT NULL,
    max_capacity INT         NOT NULL,
    occupied     INT         NOT NULL DEFAULT 0,
    CONSTRAINT chk_kennel_capacity CHECK (occupied >= 0 AND occupied <= max_capacity)
);

-- ---------------------------------------------------------------------
-- HEALTH_RECORDS: veterinary history (visits, vaccines, parasite
-- treatments, diets). Drives the 48h deadline alerts in the UI.
-- N:1 with animals.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS health_records (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    microchip_id   VARCHAR(50)  NOT NULL,
    treatment_type VARCHAR(40)  NOT NULL,
    description    VARCHAR(255),
    treatment_date DATE         NOT NULL,
    dosage         VARCHAR(50),
    CONSTRAINT fk_health_animal FOREIGN KEY (microchip_id)
        REFERENCES animals (microchip_id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------
-- ADOPTIONS: placement of one animal with one adopter.
-- Written inside a JDBC transaction together with the animal status
-- update and the audit entry (see AdoptionService.processAdoption).
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS adoptions (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animal_id      VARCHAR(50) NOT NULL,
    adopter_id     VARCHAR(50) NOT NULL,
    placement_date DATE        NOT NULL,
    CONSTRAINT fk_adoption_animal  FOREIGN KEY (animal_id)
        REFERENCES animals  (microchip_id),
    CONSTRAINT fk_adoption_adopter FOREIGN KEY (adopter_id)
        REFERENCES adopters (adopter_id)
);

-- ---------------------------------------------------------------------
-- STATUS_CHANGE_LOG: audit trail of every lifecycle transition.
-- Append-only; never updated or deleted by the application.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS status_change_log (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    microchip_id VARCHAR(50) NOT NULL,
    old_status   VARCHAR(50),
    new_status   VARCHAR(50) NOT NULL,
    change_date  TIMESTAMP   NOT NULL,
    CONSTRAINT fk_log_animal FOREIGN KEY (microchip_id)
        REFERENCES animals (microchip_id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------
-- Indexes for the most frequent lookups.
-- ---------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_animals_status    ON animals          (status);
CREATE INDEX IF NOT EXISTS idx_health_animal     ON health_records   (microchip_id);
CREATE INDEX IF NOT EXISTS idx_health_date       ON health_records   (treatment_date);
CREATE INDEX IF NOT EXISTS idx_adoptions_animal  ON adoptions        (animal_id);
CREATE INDEX IF NOT EXISTS idx_adoptions_adopter ON adoptions        (adopter_id);
CREATE INDEX IF NOT EXISTS idx_adoptions_date    ON adoptions        (placement_date);
CREATE INDEX IF NOT EXISTS idx_log_animal        ON status_change_log(microchip_id);
