-- =====================================================================
-- Pet Shelter and Adoption Management System
-- Project 11 - Software Engineering 2025/2026 - University of Cassino
--
-- Relational schema (H2, file mode: jdbc:h2:file:./data/petshelter)
--
-- This file is the documentation of the schema that the application
-- creates at start-up in dao/SchemaInitializer.java. The statements are
-- identical and in the same order, so this script can also be executed
-- manually to initialise an empty database.
--
-- Order matters: the parent tables (animals, adopters, kennels) are
-- created first, then the tables that reference them, and only after
-- that the foreign keys.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. PARENT TABLES
-- ---------------------------------------------------------------------

-- Core registry. One row per sheltered animal.
-- microchip_id is the natural business key used across the whole system.
-- animal_type discriminates the Java subclasses (Dog / Cat).
-- status: IN_OBSERVATION | UNDER_TREATMENT | READY_FOR_ADOPTION | ADOPTED
CREATE TABLE IF NOT EXISTS animals (
    microchip_id  VARCHAR(50) PRIMARY KEY,
    animal_type   VARCHAR(20),
    breed         VARCHAR(100),
    intake_date   DATE,
    estimated_age INT,
    health_status VARCHAR(50),
    photo_path    VARCHAR(255),
    status        VARCHAR(50)
);

-- People registered as potential adopters.
-- preferred_species / preferred_breed drive the compatibility matching.
CREATE TABLE IF NOT EXISTS adopters (
    adopter_id        VARCHAR(50) PRIMARY KEY,
    full_name         VARCHAR(150),
    phone             VARCHAR(40),
    preferred_species VARCHAR(40),
    preferred_breed   VARCHAR(100)
);

-- Physical shelter spaces with capacity control.
-- space_type: KENNEL | CAGE | FENCED_AREA
CREATE TABLE IF NOT EXISTS kennels (
    kennel_id    VARCHAR(50) PRIMARY KEY,
    space_type   VARCHAR(30),
    max_capacity INT,
    occupied     INT
);

-- ---------------------------------------------------------------------
-- 2. CHILD TABLES
-- ---------------------------------------------------------------------

-- Veterinary history: visits, vaccines, parasite treatments and diets.
-- Drives the medical deadline alerts shown in the JavaFX interface.
CREATE TABLE IF NOT EXISTS health_records (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    microchip_id   VARCHAR(50),
    treatment_type VARCHAR(40),
    description    VARCHAR(255),
    treatment_date DATE,
    dosage         VARCHAR(50)
);

-- Placement of one animal with one adopter. Written inside a single JDBC
-- transaction together with the animal status update and the audit entry
-- (see AdoptionService.processAdoption).
CREATE TABLE IF NOT EXISTS adoptions (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animal_id      VARCHAR(50),
    adopter_id     VARCHAR(50),
    placement_date DATE
);

-- Append-only audit trail of every lifecycle transition of an animal.
CREATE TABLE IF NOT EXISTS status_change_log (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    microchip_id VARCHAR(50),
    old_status   VARCHAR(50),
    new_status   VARCHAR(50),
    change_date  TIMESTAMP
);

-- ---------------------------------------------------------------------
-- 3. REFERENTIAL INTEGRITY AND DOMAIN INVARIANTS
--
-- Declared separately so that a database created by an earlier version
-- of the application is upgraded in place (IF NOT EXISTS).
-- ---------------------------------------------------------------------

ALTER TABLE health_records ADD CONSTRAINT IF NOT EXISTS fk_health_animal
    FOREIGN KEY (microchip_id) REFERENCES animals (microchip_id) ON DELETE CASCADE;

ALTER TABLE adoptions ADD CONSTRAINT IF NOT EXISTS fk_adoption_animal
    FOREIGN KEY (animal_id) REFERENCES animals (microchip_id);

ALTER TABLE adoptions ADD CONSTRAINT IF NOT EXISTS fk_adoption_adopter
    FOREIGN KEY (adopter_id) REFERENCES adopters (adopter_id);

ALTER TABLE status_change_log ADD CONSTRAINT IF NOT EXISTS fk_log_animal
    FOREIGN KEY (microchip_id) REFERENCES animals (microchip_id) ON DELETE CASCADE;

ALTER TABLE kennels ADD CONSTRAINT IF NOT EXISTS chk_kennel_capacity
    CHECK (occupied >= 0 AND occupied <= max_capacity);

-- ---------------------------------------------------------------------
-- 4. INDEXES for the most frequent lookups
-- ---------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_animals_status    ON animals          (status);
CREATE INDEX IF NOT EXISTS idx_health_animal     ON health_records   (microchip_id);
CREATE INDEX IF NOT EXISTS idx_health_date       ON health_records   (treatment_date);
CREATE INDEX IF NOT EXISTS idx_adoptions_animal  ON adoptions        (animal_id);
CREATE INDEX IF NOT EXISTS idx_adoptions_adopter ON adoptions        (adopter_id);
CREATE INDEX IF NOT EXISTS idx_adoptions_date    ON adoptions        (placement_date);
CREATE INDEX IF NOT EXISTS idx_log_animal        ON status_change_log(microchip_id);
